[package]
name = "default-net"
version = "0.14.1"
authors = ["shellrow <shellrow@protonmail.com>"]
edition = "2021"
description = "Cross-platform library for network interface and gateway"
repository = "https://github.com/shellrow/default-net"
readme = "README.md"
keywords = ["network"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
libc = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
# DL Open
dlopen2 = "0.4"
once_cell = "1"
# netlink
netlink-packet-core = "0.5"
netlink-packet-route = "0.15"
netlink-sys = "0.8"

[target.'cfg(windows)'.dependencies]
memalloc = "0.1.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.32.0"
features = ["Win32_Foundation","Win32_NetworkManagement_IpHelper", "Win32_Networking_WinSock"]

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
system-configuration = { git = "https://github.com/quentinvedrenne/system-configuration-rs.git", branch = "main" }

